### ISSUE TITLE
[New Game]: Little Red Riding Hood

### ISSUE THREAD

**Issue by sabhisharma-ise** [GameSphere-MultiPlayer/GameSphere#761]
## Description

In this game, Help little red to escape the wolf by tapping to jump pits!

## Screenshot Section

![Riding_Hood](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100849696/6df810c3-9e65-468c-a9f6-a8c7c13877e4)

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100849696/a1352f10-83e7-4648-a160-47f8396f29d1

## Task

- [X] Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X] #766
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Aman1-coder** [comment]
@Durgesh4993 Please remember which levels are you using
