### ISSUE TITLE
Platform game engine

### ISSUE THREAD

**Issue by SimranLahrani842** [GameSphere-MultiPlayer/GameSphere#852]
## Game Name
Reach the ball to the goal with the help of arrow keys 

## Description

Move the ball through the maze to reach to its goal

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

**Comment by Durgesh4993** [comment]
@SimranLahrani842 please add a screenshort or demo vedio
